services:
  nestjs_api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD: ${DB_PASSWORD}
      - POSTGRES_USER: ${DB_USER}
      - POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432