export const USER_NOT_FOUND = 'User not found'
export const CATEGORY_NOT_FOUND = 'Category not found'
export const COMMENT_NOT_FOUND = 'Comment not found'
export const EVENT_NOT_FOUND = 'Event not found'
export const TICKET_NOT_FOUND = 'Ticket not found'