export const USER_NOT_FOUND = 'User not found'
export const CATEGORY_NOT_FOUND = 'Category not found'
export const COMMENT_NOT_FOUND = 'Comment not found'
export const EVENT_NOT_FOUND = 'Event not found'
export const TICKET_NOT_FOUND = 'Ticket not found'
export const PLACE_NOT_FOUND = 'Place not found'
export const POST_NOT_FOUND = 'Post not found'
export const EMAIL_DOES_NOT_EXIST = 'Email does not exist'
export const INCORRECT_PASSWORD = 'Incorrect password'
export const PURCHASE_NOT_FOUND = 'Purchase not found'

export const OPTIONAL_INT_PIPE_NUMBER = '$key should be a number';
export const USER_NOT_ACTIVE = 'User is not active';
export const INVALID_PASSWORD = 'Invalid password';
export const EMAIL_ALREADY_EXISTS = 'Email already exists';
export const USERNAME_ALREADY_EXISTS = 'Username already exists';
export const ERROR_SENDING_EMAIL = 'Error sending email';
export const INSUFFICIENT_DATA = 'Insufficient data provided to send email. Please ensure all required parameters are included.'
export const FORBIDDEN_EXCEPTION = 'Not permission.'
export const UNAUTHORIZED_EXCEPTION = 'Not authenticated.'