name: Production deploy to GAE
concurrency: production

on:
  push:
    tags:
      - 'prod-v*.*.*'

jobs:
  deploy_to_gae_backend:
    name: Deploying to Google Cloud Backend
    runs-on: ubuntu-latest

    steps:
      # Checkout the entire repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Set up Cloud SDK
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ secrets.PROD_GCP_PROJECT_ID }}

      # Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.PROD_GCP_CREDENTIALS }}

      # Create .env file
      - name: Create .env file
        run: |
          cd event-spot
          echo "GOOGLE_APPLICATION_CREDENTIALS=gcloud-key.json" >> .env
          echo "PORT=${{ secrets.PROD_PORT }}" >> .env
          echo "DATABASE_URL=${{ secrets.PROD_DATABASE_URL }}" >> .env
          echo "JWT_SECRET=${{ secrets.PROD_JWT_SECRET }}" >> .env

      # Install dependencies
      - name: Install dependencies
        run: |
          cd event-spot
          npm install

      # Build project
      - name: Build Project
        run: |
          cd event-spot
          npm run build

      # Deploy to App Engine
      - name: Deploy to App Engine
        run: |
          cd event-spot
          gcloud app deploy app.yaml --quiet
