jobs:
  deploy_to_gae_backend:
    name: Deploying to Google Cloud Backend
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js y npm
      - name: Setup Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Paso 3: Moverse al directorio correcto
      - name: Change directory to project folder
        run: cd event-spot

      # Paso 4: Configurar gcloud CLI (instalarlo)
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ secrets.PROD_GCP_PROJECT_ID }}

      # Paso 5: Autenticarse en Google Cloud
      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.PROD_GCP_CREDENTIALS }}

      # Paso 6: Crear el archivo .env y escribir los secretos en él
      - name: Create .env file
        run: |
          cd event-spot
          echo "GOOGLE_APPLICATION_CREDENTIALS=gcloud-key.json" >> .env
          echo "PORT=${{ secrets.PROD_PORT }}" >> .env
          echo "DATABASE_URL=${{ secrets.PROD_DATABASE_URL }}" >> .env
          echo "JWT_SECRET=${{ secrets.PROD_JWT_SECRET }}" >> .env

      # Paso 7: Instalar dependencias
      - name: Install dependencies
        run: |
          cd event-spot
          npm install

      # Paso 8: Ejecutar el build
      - name: Build Project
        run: |
          cd event-spot
          npm run build

      # Paso 9: Desplegar a App Engine
      - name: Deploy to App Engine
        run: |
          cd event-spot
          gcloud app deploy app.yaml --quiet
